version: '3.8'

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
      - dblogs:/var/log/postgresql
    networks:
      - mynetwork

  service-1:
    build:
      context: ./
    restart: always
    volumes:
      - ./src:/app/src
    ports:
      - '3000:3000'
    networks:
      - mynetwork

volumes:
  dbdata:
  dblogs:

networks:
  mynetwork:
    driver: bridge
