version: '3.8'
services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
      - dblogs:/var/log/postgresql
    networks:
      - mynetwork

volumes:
  dbdata:
  dblogs:
  appdata:

networks:
  mynetwork:
